apiVersion: v1
kind: PersitentVolumeClaim
metadata:
  name: pvc-data
  namespace: todoapp
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  capacity:
  resources:
    requests:
      storage: 1Gi